// jest.config.js
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/tests', '<rootDir>'],
  testMatch: ['**/*.test.js', '**/*.test.ts'],
  collectCoverageFrom: [
    'controllers/**/*.ts',
    'lib/**/*.ts',
    'middleware/**/*.ts',
    'models/**/*.ts',
    'routes/**/*.ts',
    'services/**/*.ts',
    'types/**/*.ts',
    'utils/**/*.ts',
    'workers/**/*.ts',
    'index.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/*.d.ts',
    '!**/tests/**',
    '!**/coverage/**',
    '!swagger.ts',
    // Exclude backup service files until it is decided whether to keep or remove the backup feature
    // TODO: https://github.com/iKozay/TrackMyDegree/issues/228
    '!services/backup/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['lcov', 'text', 'text-summary', 'html'],
  moduleFileExtensions: ['ts', 'js', 'json'],
  transform: {
    '^.+\\.ts$': [
      'ts-jest',
      {
        tsconfig: 'tsconfig.test.json',
        isolatedModules: false,
      },
    ],
    '^.+\\.js$': 'babel-jest',
  },
  transformIgnorePatterns: [],
  moduleNameMapper: {
    '^@controllers/(.*)$': '<rootDir>/controllers/$1',
    '^@controllers$': '<rootDir>/controllers/index',
    '^@lib/(.*)$': '<rootDir>/lib/$1',
    '^@middleware/(.*)$': '<rootDir>/middleware/$1',
    '^@models/(.*)$': '<rootDir>/models/$1',
    '^@models$': '<rootDir>/models/index',
    '^@routes/(.*)$': '<rootDir>/routes/$1',
    '^@services/(.*)$': '<rootDir>/services/$1',
    '^@types/(.*)$': '<rootDir>/types/$1',
    '^@utils/(.*)$': '<rootDir>/utils/$1',
  },
  setupFiles: ['<rootDir>/tests/setup.js'],
  collectCoverage: true,
  coverageThreshold: {
    global: {
      branches: 0,
      functions: 0,
      lines: 0,
      statements: 0,
    },
  },
  testPathIgnorePatterns: ['<rootDir>/dist/', '/tests/integration/'],
};
