import HTTP from '@utils/httpCodes';
import express, { Request, Response } from 'express';
import { authController, UserType } from '@controllers/authController';
import { jwtService } from '@services/jwtService';

const router = express.Router();

const INTERNAL_SERVER_ERROR = 'Internal server error';
const EMPTY_REQUEST_BODY = 'Request body cannot be empty';

/**
 * POST /auth/login - User login
 */
router.post('/login', async (req: Request, res: Response) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      res.status(HTTP.BAD_REQUEST).json({
        error: 'Email and password are required',
      });
      return;
    }

    const user = await authController.authenticate(email, password);

    if (!user) {
      res.status(HTTP.UNAUTHORIZED).json({
        error: 'Incorrect email or password',
      });
      return;
    }

    const accessToken = jwtService.generateToken({
      orgId: process.env.JWT_ORG_ID || '',
      userId: user._id,
      type: user.type,
    });
    const refreshToken = jwtService.generateToken(
      {
        orgId: process.env.JWT_ORG_ID || '',
        userId: user._id,
        type: user.type,
      },
      true,
    );

    const accessCookie = jwtService.setAccessCookie(accessToken);
    const refreshCookie = jwtService.setRefreshCookie(refreshToken);

    res.cookie(accessCookie.name, accessCookie.value, accessCookie.config);
    res.cookie(refreshCookie.name, refreshCookie.value, refreshCookie.config);

    res.status(HTTP.OK).json(user);
  } catch (error) {
    console.error('Error in POST /auth/login', error);
    res.status(HTTP.SERVER_ERR).json({ error: INTERNAL_SERVER_ERROR });
  }
});

/**
 * POST /auth/refresh - User login automatically via refresh token
 */
router.post('/refresh', async (req: Request, res: Response) => {
  const token = req.cookies?.refresh_token;
  if (!token)
    return res
      .status(HTTP.UNAUTHORIZED)
      .json({ error: 'Missing refresh token' });

  try {
    const payload = jwtService.verifyRefreshToken(token);
    if (!payload)
      return res
        .status(HTTP.UNAUTHORIZED)
        .json({ error: 'Invalid or expired refresh token' });

    // Validate user still exists
    const user = await authController.getUserById(payload.userId);
    if (!user) {
      return res
        .status(HTTP.UNAUTHORIZED)
        .json({ error: 'User does not exist' });
    }

    const newAccessToken = jwtService.generateToken({
      orgId: payload.orgId,
      userId: payload.userId,
      type: payload.type,
    });
    const newRefreshToken = jwtService.generateToken(
      {
        orgId: payload.orgId,
        userId: payload.userId,
        type: payload.type,
      },
      true,
    );

    const accessCookie = jwtService.setAccessCookie(newAccessToken);
    const refreshCookie = jwtService.setRefreshCookie(newRefreshToken);

    res.cookie(accessCookie.name, accessCookie.value, accessCookie.config);
    res.cookie(refreshCookie.name, refreshCookie.value, refreshCookie.config);

    res.status(HTTP.OK).json(user);
  } catch (error) {
    console.error('Error in POST /auth/refresh', error);
    res.status(HTTP.SERVER_ERR).json({ error: INTERNAL_SERVER_ERROR });
  }
});

/**
 * POST /auth/refresh - User logout and clear all cookies
 */
router.post('/logout', (req: Request, res: Response) => {
  res.clearCookie('access_token', { path: '/' });
  res.clearCookie('refresh_token', { path: '/auth/refresh' });
  res.status(200).json({ message: 'Logged out' });
});

/**
 * POST /auth/signup - User registration
 */
router.post('/signup', async (req: Request, res: Response) => {
  try {
    if (!req.body || Object.keys(req.body).length === 0) {
      res.status(HTTP.BAD_REQUEST).json({
        error: EMPTY_REQUEST_BODY,
      });
      return;
    }

    const { email, password, fullname, type } = req.body;

    if (!email || !password || !fullname || !type) {
      res.status(HTTP.BAD_REQUEST).json({
        error: 'Email, password, fullname, and type are required',
      });
      return;
    }

    // Validate user type
    if (!Object.values(UserType).includes(type)) {
      res.status(HTTP.BAD_REQUEST).json({
        error: 'Invalid user type',
      });
      return;
    }

    const userInfo = {
      email,
      password, // Plain password - will be hashed in controller
      fullname,
      type: type as UserType,
      _id: '', // Will be generated by controller
    };

    const result = await authController.registerUser(userInfo);

    if (result) {
      const accessToken = jwtService.generateToken({
        orgId: process.env.JWT_ORG_ID || '',
        userId: result._id,
        type: result.type as UserType,
      });
      const refreshToken = jwtService.generateToken(
        {
          orgId: process.env.JWT_ORG_ID || '',
          userId: result._id,
          type: result.type as UserType,
        },
        true,
      );

      const accessCookie = jwtService.setAccessCookie(accessToken);
      const refreshCookie = jwtService.setRefreshCookie(refreshToken);

      res.cookie(accessCookie.name, accessCookie.value, accessCookie.config);
      res.cookie(refreshCookie.name, refreshCookie.value, refreshCookie.config);

      res.status(HTTP.CREATED).json(result);
    } else {
      res.status(HTTP.CONFLICT).json({
        error: 'User with this email already exists',
      });
    }
  } catch (error) {
    console.error('Error in POST /auth/signup', error);
    res.status(HTTP.SERVER_ERR).json({ error: INTERNAL_SERVER_ERROR });
  }
});

/**
 * POST /auth/forgot-password - Initiate password reset
 */
router.post('/forgot-password', async (req: Request, res: Response) => {
  try {
    if (!req.body?.email) {
      res.status(HTTP.BAD_REQUEST).json({
        error: EMPTY_REQUEST_BODY,
      });
      return;
    }

    const { email } = req.body;
    const result = await authController.forgotPassword(email);

    res.status(HTTP.ACCEPTED).json(result);
  } catch (error) {
    console.error('Error in POST /auth/forgot-password', error);
    res.status(HTTP.SERVER_ERR).json({ error: INTERNAL_SERVER_ERROR });
  }
});

/**
 * POST /auth/reset-password - Reset password with OTP
 */
router.post('/reset-password', async (req: Request, res: Response) => {
  try {
    if (!req.body) {
      res.status(HTTP.BAD_REQUEST).json({
        error: EMPTY_REQUEST_BODY,
      });
      return;
    }

    const { email, token, newPassword } = req.body;

    if (!email || !token || !newPassword) {
      res.status(HTTP.BAD_REQUEST).json({
        error: 'Email, token, and newPassword are required',
      });
      return;
    }

    const result = await authController.resetPassword(token, newPassword);
    if (result) {
      res.status(HTTP.ACCEPTED).json({
        message: 'Password reset successfully',
      });
    } else {
      res.status(HTTP.UNAUTHORIZED).json({
        error: 'Invalid or expired reset link',
      });
    }
  } catch (error) {
    console.error('Error in POST /auth/reset-password', error);
    res.status(HTTP.SERVER_ERR).json({ error: INTERNAL_SERVER_ERROR });
  }
});

export default router;
