openapi: 3.0.0
info:
  title: Deficiency API
  version: 1.0.0
  description: API for managing user deficiencies

paths:
  /deficiency/create:
    post:
      summary: Create a new deficiency
      tags:
        - Deficiency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coursepool:
                  type: string
                  example: 'SOEN-Core'
                user_id:
                  type: string
                  example: '12345'
                creditsRequired:
                  type: number
                  example: 6
      responses:
        201:
          description: Deficiency created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeficiencyResponse'
        400:
          description: Invalid input
        403:
          description: Forbidden (service error)
        500:
          description: Internal server error

  /deficiency/getAll:
    post:
      summary: Get all deficiencies for a user
      tags:
        - Deficiency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  example: '12345'
      responses:
        200:
          description: Deficiencies retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeficiencyResponse'
        400:
          description: Invalid input
        403:
          description: Forbidden (service error)
        500:
          description: Internal server error

  /deficiency/delete:
    post:
      summary: Delete a deficiency for a user
      tags:
        - Deficiency
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coursepool:
                  type: string
                  example: 'SOEN-Core'
                user_id:
                  type: string
                  example: '12345'
      responses:
        200:
          description: Deficiency deleted successfully
        400:
          description: Invalid input
        403:
          description: Forbidden (deficiency does not exist)
        500:
          description: Internal server error

components:
  schemas:
    DeficiencyResponse:
      type: object
      properties:
        message:
          type: string
          example: 'Deficiency created successfully'
        deficiency:
          type: object
          properties:
            id:
              type: string
              example: 'd123'
            user_id:
              type: string
              example: '12345'
            coursepool:
              type: string
              example: 'SOEN-Core'
            creditsRequired:
              type: number
              example: 6
            createdAt:
              type: string
              format: date-time
              example: '2025-10-04T12:00:00Z'
