declare namespace TimelineTypes {
  export interface Timeline {
    /** When saving a new timeline, the id can be omitted. It will be generated. */
    id?: string;
    user_id: string;
    name: string;
    /** This field is automatically set/updated when the timeline is saved. */
    last_modified?: Date | string;
    items: TimelineItem[];
  }

  export interface TimelineItem {
    /** Optional id generated by the controller */
    id?: string;
    season: "fall" | "winter" | "summer1" | "summer2" | "fall/winter" | "summer";
    year: number;
    /** Array of course codes (as strings) associated with this timeline item */
    courses: string[];
  }
}

export default TimelineTypes;
