# This workflow connects to the server, pulls latest changes and builds the docker image on the spot.
# This is not optimial because building the image in prod can lead to downtime if the build takes too long (and it does take time to build).

name: Deploy

on:
  push:
    branches:
      - main # So here it does not wait until system tests pass. We can change this if we want to only deploy after tests pass (merge the 2 workflows)
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # A quick search shows that Droplet is a term used by DigitalOcean for their virtual private servers (VPS).
      # This step connects to the Droplet using SSH and deploys the latest changes using Docker Compose.
      - name: SSH into Droplet and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/TrackMyDegree
            git pull origin main
            docker-compose down
            docker-compose up --build -d
